Fix de los tipos de recursos
tesis-cabal-cugno-moreyra/webapp pull request #72
Opened 2021-03-21 00:43 UTC by cabaljoaquin

Se corrigió a la hora de seleccionar los tipos de recursos, que aparezcan los nuevos en todos los lados disponibles.

![image](https://user-images.githubusercontent.com/63656558/111890095-3d017380-89c5-11eb-9b81-e858fe757b4f.png)

2021-03-21 00:46 UTC, fmoreyra commented on src/components/IncidentResourceList.vue
> +      let incidentAbstractions = this.domainConfig.incidentAbstractions;
Yo armaría una acción de vuex, en el domain-config, que te traiga una request (o el objeto domain-config completo) y te devuelva el listado de resource types. Entonces, en todos los lugares donde se hace este código, directamente llamar al action.

2021-04-29 21:22 UTC, Gnoq requested changes
Opino igual que Facu, encapsular esa funcionalidad en Vuex o agregarlo en las utils o services, para no repetirlo nomás.

2021-04-29 21:23 UTC, Gnoq commented
PD: hay que cambiar el PR, que apunte a sprint-7 en lugar de sprint-6.

2021-06-21 23:16 UTC, fmoreyra approved these changes

2021-06-21 23:17 UTC, Gnoq approved these changes
Ok!

2021-06-21 23:17 UTC, merged